FROM node:24.0 AS builder
WORKDIR /app

COPY package*.json ./
RUN npm install

COPY ../ ./
RUN npm run build

# Stage 2: Serve with nginx
FROM nginx:latest

COPY --from=builder /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]