FROM node:24.15
WORKDIR /app
COPY ../package*.json ./
RUN npm install
COPY ../ ./
RUN npm run build

FROM nginx
COPY --from=builder /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "deaemon off;"]